backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts"
    label: "posts"
    folder: "content/posts/"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields: 
      - {label: "path", name: "path", widget: "string", default: "FName-LName"}
      - {label: "cover", name: "cover", widget: "string", default: "",required: false}
      - {label: "date", name: "date", widget: "datetime", default: ""}
      - {label: "title", name: "title", widget: "string", default: "First Last"}
      - {label: "published", name: "published", widget: "boolean", default: false}
      - {label: "tags", name: "tags", widget: "list", default: [] }
      - {label: "Body", name: "body", widget: "markdown"}
